name: Feature Request
description: Template for new feature implementation
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: Describe the feature you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: |
        As a [type of user],
        I want [goal],
        So that [benefit/value].
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: List the technical requirements for this feature
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: api-endpoints
    attributes:
      label: API Endpoints
      description: If applicable, describe the API endpoints needed
      placeholder: |
        Method: GET/POST/PUT/DELETE
        Path: /api/endpoint
        Request Body: {
            "example": "value"
        }
        Response: {
            "example": "value"
        }
    validations:
      required: false

  - type: textarea
    id: database-changes
    attributes:
      label: Database Changes
      description: List any database changes needed
      placeholder: |
        - New models/schemas
        - Field modifications
        - Migrations needed
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be satisfied
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Tests are written and passing
        - [ ] Documentation is updated
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
    validations:
      required: false
